# -*- coding: utf-8 -*-
"""Tek_Cift.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cds9l5HuiEaVzqQzjgeEkXnRZSqtXUe8
"""

word = "bilgisayar" #input("Please write a word :").lower()
alfabe = 'abcçdefgğhıijklmnoöprsştuüvyz'
#print(list(alfabe))
sıralı_alfabe = dict(zip((list(alfabe)),(list(range(1,30)))))
sıralı_alfabe
output = 0

for i in word:
  output += sıralı_alfabe[i]
if output % 2:
  print("False")
else:
  print("True")